env:
    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: 
    TG_TOKEN: 

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Android CI"
  timeout_in: 2000m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      #image: apon77/aosp
      cpu: 8
      memory: 32G

  Checks_script:
      - curl -sL https://raw.githubusercontent.com/lirkyo/AOSP-CI/main/scripts/checks.sh | bash

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/lirkyo/AOSP-CI/main/scripts/sync.sh | bash

  Build_script:
      - curl -sL https://raw.githubusercontent.com/lirkyo/AOSP-CI/main/scripts/build.sh | bash

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - curl -sL https://raw.githubusercontent.com/lirkyo/AOSP-CI/main/scripts/upload.sh | bash
